mytest/mytest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytest/shop/urls.py
from django.conf.urls import url
from shop import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^categories/$', views.category, name='category'),
    url(r'^category/(?P<category_id>[0-9])/$', views.category_detail, name='category_detail'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^cart/$', views.add_to_cart, name='cart'),
]

mytest/shop/models.py
from django.db import models


class Good(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='имя товара')
    price = models.PositiveIntegerField(verbose_name='цена')
    timestamp = models.DateTimeField(auto_now=True, verbose_name='дата добавление')
    category = models.ForeignKey('Category', blank=True, null=True)
    tag = models.ManyToManyField('Tag', blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='изображение')

    class Meta:
        ordering = ['-timestamp']
        verbose_name = "Товар"
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    category = models.ForeignKey('Category', blank=True, null=True)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class User(models.Model):
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)

mytest/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(label=u'имя')
    email = forms.EmailField(max_length=255, label=u'email')
    password = forms.PasswordInput()

    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2')

mytest/shop/views.py
from django.shortcuts import render, redirect, HttpResponse
from shop.models import Good, Tag, Category
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User

from shop.forms import SignUpForm


def home(request):
    goods = Good.objects.all()
    context = {
        'goods': goods
    }
    return render(request, 'shop/goods.html', context)


def category(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'shop/categories.html', context)


def category_detail(request, category_id):
    goods = Good.objects.filter(category=category_id)
    category_name = Category.objects.get(pk=category_id)
    tags = Tag.objects.filter(category=category_id)
    context = {
        'goods': goods,
        'category': category_name,
        'tags': tags
    }
    return render(request, 'shop/category_detail.html', context)


def login_view(request):
    if request.POST:
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/shop/')
        else:
            error_message = {
                'error': 'неверный данные для входа'
            }
            return redirect('/shop/login', error_message)
    return render(request, 'shop/login.html')


def logout_view(request):
    logout(request)
    return redirect('/shop/')


def registration(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/shop/')
    else:
        form = SignUpForm()
    if request.user.is_authenticated:
        return redirect('/shop/login')
    else:
        return render(request, 'shop/registration.html', {'form': form})


def add_to_cart(request):
    if 'cart' not in request.session:
        request.session['cart'] = id
        return HttpResponse(request.session['cart'])
    return HttpResponse('cart is empty')
    # if request.user.is_authenticated:
    #     user_id = request.user.id
    #     request.session.set_expiry(60)
    #     request.session['user_id'] = user_id
    #     user = User.objects.get(pk=request.session['user_id'])
    #     message = 'Hello '+user.email
    #     return HttpResponse(message)
    # else:
    #     return HttpResponse('you have to log in')

mytest/shop/templates/shop/categories.html
{% extends 'shop/main.html' %}

{% block content %}
    <h2>Категории</h2>
    {% for category in categories %}
        <p><a href="{% url 'shop:category_detail' category.id %}">{{ category.name }}</a></p>
    {% endfor %}
{% endblock %}

mytest/shop/templates/shop/category_detail.html
{% extends 'shop/main.html' %}

{% block goods %}
    {% if goods %}
        <h2>Категория >{{ category.name }}</h2>
        <div class="tags">
            <p>tags</p>
            {% for tag in tags %}
                <a class="btn btn-default tag" href="#" role="button" id="{{ tag.id }}">{{ tag.name }}</a>
            {% endfor %}
        </div>

        {% include 'shop/include/goods.html' %}

    {% else %}
        <h3>Нет товаров в этой категории</h3>
    {% endif %}
{% endblock %}

mytest/shop/templates/shop/goods.html
{% extends 'shop/main.html' %}

{% block goods %}

     {% include 'shop/include/goods.html' %}

{% endblock %}

mytest/shop/templates/shop/include/goods.html
{% for good in goods %}
    <div class="col-md-4">
        <img src="{{ good.image.url }}" height="300" width="250">
        <h2>{{ good.name }}</h2>
        <p>{{ good.price }} руб</p>
        {% for tag in good.tag.all %}
            {{ tag }}
        {% endfor %}
{#        <p><a class="btn btn-default" href="#" role="button" data-id="{{ good.pk }}">В корзину</a></p>#}
        <form action="{% url 'shop:cart' %}">
            <input type="button" value="add to cart" n>
        </form>
    </div>
{% endfor %}

mytest/shop/templates/shop/login.html
{% extends 'shop/main.html' %}

{% block content %}
    {% if error %} {{ error }}{% endif %}
    <form action="{% url 'shop:login' %}" method="post">
    {% csrf_token %}
        <label for="">
            email
            <input type="email" name="email">
        </label>
        <label for="">
            password
            <input type="password" name="password">
        </label>
        <input type="submit">
        <input type="reset">
    </form>
{% endblock %}

mytest/shop/templates/shop/main.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Simple shop</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/main.css' %}">
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://localhost:8000/shop/">Simple shop</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

        </div>
    </div>
</nav>

<div class="jumbotron">
    <div class="container">
        <div class="menu">
            <li><a href="{% url 'shop:registration' %}">регистрация</a></li>
            <li><a href="{% url 'shop:login' %}">авторизация</a></li>
            <li><a href="{% url 'shop:category' %}">категории</a></li>
            <li><a href="{% url 'shop:cart' %}">корзина</a></li>
        </div>
    </div>
</div>

<div class="container">
    {% if user.is_authenticated %}
        Привет, {{ user.email }}
        <a href="{% url 'shop:logout' %}">выйти</a>
    {% endif %}

    {% block content %}{% endblock %}

    <div class="row">
        {% block goods %}{% endblock %}
    </div>

    <hr>

    <footer>
        <p>© 2016 Company, Inc.</p>
    </footer>
</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'shop/js/main.js' %}"></script>
</body>
<autoscroll></autoscroll>
</html>

mytest/shop/templates/shop/registration.html
{% extends 'shop/main.html' %}
<h2>Sign up</h2>
{% if user.is_authenticated %}
    Привет, {{ user.email }}
{% else %}
    {% block content %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign up</button>
        </form>
    {% endblock %}
{% endif %}